trigger:
- none # Sem integração com Git, o pipeline pode ser iniciado manualmente

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildFrontend
    displayName: 'Build Frontend (Vue.js)'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Instalar Node.js'

    - script: |
        npm install
      displayName: 'Instalar dependências Vue.js'

    - script: |
        npm run build
      displayName: 'Build do App Vue.js'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'dist'  # Diretório onde o Vue.js gera os arquivos de build
        artifact: 'drop'
      displayName: 'Publicar artefato de build'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: DeployFrontend
    displayName: 'Deploy Frontend para servidor mock'
    steps:
    - task: CopyFiles@2
      inputs:
        contents: '**'
        targetFolder: '/var/www/html' # Caminho do servidor simulado
      displayName: 'Copiar arquivos para mock server'
      
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '/var/www/html'
        artifact: 'deploy'
      displayName: 'Publicar artefato de deploy'
