trigger: none  # Não queremos que o pipeline rode automaticamente com base em algum repositório

pool:
  name: 'MySelfHostedPool'

steps:
  - script: echo "Iniciando pipeline de demonstração"
    displayName: "Exibir mensagem de início"

  - script: echo "Executando a segunda etapa do pipeline"
    displayName: "Segunda etapa"

  - script: echo "Pipeline completo!"
    displayName: "Finalizar pipeline"
